cloud:
    aws:
      region:
        static: us-east-1
        auto: false
      credentials:
          access-key: AKIAW3MEAMZTNISYYWUC
          secret-key: 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
      end-point:
        uri: https://sqs.us-east-1.amazonaws.com/471112640102/FirstQ
#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
#      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
